# Analise Exploratoria - Indicador Crianca Alfabetizada

Explora dados da Base dos Dados sobre o Indicador de Alfabetizacao por municipio, UF e Brasil.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Carrega amostra local para exploracao inicial
df = pd.read_csv('/Users/gustavosoares/Documents/Pos Tech/tech_challeng/tech_challeng_2/data/raw/inep/br_inep_avaliacao_alfabetizacao_alunos.csv')
df.head()

,ano,id_municipio,id_escola,id_aluno,caderno,serie,rede,presenca,preenchimento_caderno,alfabetizado,proficiencia,peso_aluno
0,2023,2211001,60006431,22034277,1,2,3,0,0,0,NaN,NaN
1,2023,4205407,60034824,42034973,1,2,2,0,0,0,NaN,NaN
2,2023,4301602,60039942,43025289,1,2,3,0,0,0,NaN,NaN
3,2024,1302603,60000925,13033107,1,2,2,0,0,0,NaN,NaN
4,2024,1502152,60003041,15022792,1,2,3,0,0,0,NaN,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3867999 entries, 0 to 3867998
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ano                    int64
 1   id_municipio           int64
 2   id_escola              int64
 3   id_aluno               int64
 4   caderno                int64
 5   serie                  int64
 6   rede                   int64
 7   presenca               int64
 8   preenchimento_caderno  int64
 9   alfabetizado           int64
 10  proficiencia           float64
 11  peso_aluno             float64
dtypes: float64(2), int64(10)
memory usage: 354.1 MB

In [ ]:
print(df.isnull().sum())

ano                           0
id_municipio                  0
id_escola                     0
id_aluno                      0
caderno                       0
serie                         0
rede                          0
presenca                      0
preenchimento_caderno         0
alfabetizado                  0
proficiencia             513338
peso_aluno               513338
dtype: int64

In [5]:
print(df.columns)

Index(['ano', 'id_municipio', 'id_escola', 'id_aluno', 'caderno', 'serie',
       'rede', 'presenca', 'preenchimento_caderno', 'alfabetizado',
       'proficiencia', 'peso_aluno'],
      dtype='object')

In [6]:
print(df.shape)

(3867999, 12)

In [7]:
print(df.nunique())

ano                            2
id_municipio                5548
id_escola                  42811
id_aluno                 2352328
caderno                       22
serie                          1
rede                           3
presenca                       2
preenchimento_caderno          2
alfabetizado                   2
proficiencia             1299544
peso_aluno                 70528
dtype: int64

In [8]:
nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "total": len(df),
    "pct_nulos": (df.isna().mean() * 100).round(2)
}).sort_values("pct_nulos", ascending=False)

nulos

                        nulos    total  pct_nulos
proficiencia           513338  3867999      13.27
peso_aluno             513338  3867999      13.27
ano                         0  3867999       0.00
id_municipio                0  3867999       0.00
id_escola                   0  3867999       0.00
id_aluno                    0  3867999       0.00
caderno                     0  3867999       0.00
serie                       0  3867999       0.00
rede                        0  3867999       0.00
presenca                    0  3867999       0.00
preenchimento_caderno       0  3867999       0.00
alfabetizado                0  3867999       0.00